In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [3]:
print (arr1)

[ 6.   7.5  8.   0.   1. ]


In [4]:
data2 = [range(1, 5), range(5, 9)]
print(data2)
arr2 = np.array(data2)
print(arr2)

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [5]:
data2[0] + data2[1]

[1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
np.array(data2[0]) + np.array(data2[1])

array([ 6,  8, 10, 12])

In [7]:
np.array(data2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.array(data2[0]) + np.array(data2[1])

array([ 6,  8, 10, 12])

In [9]:
arr2.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int64')

In [12]:
arr2.ndim

2

In [13]:
arr2.shape    # (2, 4) - axis 0 is rows, axis 1 is columns

(2, 4)

In [14]:
arr2.size

8

In [15]:
len(arr2)

2

In [16]:
arr1**2

array([ 36.  ,  56.25,  64.  ,   0.  ,   1.  ])

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2 + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [19]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [20]:
np.linspace(0, 5, 11)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [21]:
a = np.arange(10000)

In [22]:
timeit aa = [x + y for x, y in zip(a,a)]

100 loops, best of 3: 3.79 ms per loop


In [23]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [24]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [25]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [26]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [27]:
np.logspace(0, 3, 4)

array([    1.,    10.,   100.,  1000.])

In [28]:
int_array = np.arange(5)
int_array

array([0, 1, 2, 3, 4])

In [29]:
float_array = int_array.astype(float)
float_array

array([ 0.,  1.,  2.,  3.,  4.])

In [30]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
arr1[0]

6.0

In [33]:
arr2[0]

array([1, 2, 3, 4])

In [34]:
arr2[0, 3]

4

In [35]:
arr2[0][3]

4

In [36]:
arr2[:, 0]    # all rows, column 0: returns a 1d array

array([1, 5])

In [37]:
arr2[:, 0:1]    # all rows, column 0: returns a 2d array

array([[1],
       [5]])

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5:8]

array([5, 6, 7])

In [40]:
arr[5:8] = 12    # all three values are overwritten with 12

In [41]:
arr_view = arr[5:8]         # creates a "view" on arr, not a copy

In [42]:
arr_view

array([12, 12, 12])

In [43]:
arr_view[:] = 13
arr_view

array([13, 13, 13])

In [44]:
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

In [45]:
arr_copy = arr[5:8].copy()
arr_copy

array([13, 13, 13])

In [46]:
names = np.array(["Darin", "Christine", "Jett", "Hwanie"])

In [47]:
names == "Darin"

array([ True, False, False, False], dtype=bool)

In [48]:
names[names != "Darin"]

array(['Christine', 'Jett', 'Hwanie'], 
      dtype='|S9')

In [49]:
(names == "Darin") | (names == "Jett")

array([ True, False,  True, False], dtype=bool)

In [50]:
names[names != "Darin"] = "Darin's Crew"

In [51]:
names

array(['Darin', "Darin's C", "Darin's C", "Darin's C"], 
      dtype='|S9')

In [52]:
np.unique(names)

array(['Darin', "Darin's C"], 
      dtype='|S9')

In [53]:
nums = np.arange(5)
nums

array([0, 1, 2, 3, 4])

In [54]:
nums * 10

array([ 0, 10, 20, 30, 40])

In [55]:
nums = np.sqrt(nums)

In [56]:
nums

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ])

In [57]:
np.ceil(nums)

array([ 0.,  1.,  2.,  2.,  2.])

In [58]:
nums + np.arange(5)

array([ 0.        ,  2.        ,  3.41421356,  4.73205081,  6.        ])

In [59]:
np.maximum(nums, np.array([1, -2, 3, -4, 5]))

array([ 1.        ,  1.        ,  3.        ,  1.73205081,  5.        ])

In [60]:
rnd = np.random.randn(4, 2)

In [61]:
rnd

array([[-0.15497653,  1.50552851],
       [-0.30853572, -0.55929615],
       [-0.6334276 , -2.13549997],
       [ 1.25347882, -1.28515876]])

In [62]:
rnd.mean()

-0.2897359257548211

In [63]:
rnd.std()

1.1297952179461306

In [64]:
rnd.argmin()

5

In [65]:
rnd.sum()

-2.3178874060385688

In [66]:
rnd.sum(axis=0)

array([ 0.15653897, -2.47442637])

In [67]:
rnd.sum(axis=1)

array([ 1.35055198, -0.86783188, -2.76892757, -0.03167994])

In [68]:
N = 50

x = np.random.rand(N)
y = np.random.rand(N)
colors = np.random.rand(N)
area =30+(70*np.random.rand(N)) # 30 to 100 point radiuses

plt.scatter(x, y, s=area, c=colors,)
plt.show()

In [69]:
np.where(rnd > 0, 2, -2)

array([[-2,  2],
       [-2, -2],
       [-2, -2],
       [ 2, -2]])

In [75]:
np.where(rnd > 0, 2, -2)

array([[-2,  2],
       [-2, -2],
       [-2, -2],
       [ 2, -2]])

In [74]:
(rnd > 0).sum()             # counts number of positive values

2

In [76]:
(rnd > 0).any()             # checks if any value is True

True

In [77]:
(rnd > 0).all()             # checks if all values are True

False

In [78]:
nums = np.arange(32)
nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [79]:
nums.reshape(8, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [80]:
nums.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [81]:
nums.flatten()               # flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [85]:
np.random.seed(12234)

In [86]:
np.random.rand(2, 3)

array([[ 0.00630595,  0.20303476,  0.76478993],
       [ 0.55513384,  0.74358546,  0.93777808]])

In [87]:
np.random.randn(10)

array([ -2.79962074e-01,   1.31281104e+00,  -9.27155784e-01,
        -4.01302169e-01,  -2.31085929e+00,  -2.08460156e+00,
         4.59241643e-01,   1.62191344e+00,   1.94515120e-01,
        -2.08631547e-03])

In [88]:
np.random.randint(0, 2, 10) # 0 or 1

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1])