In [17]:
'''
Our KNN algorithm
'''

'\nOur KNN algorithm\n'

In [18]:
# imports go here
import pandas as pd
import numpy as np

In [19]:
'''
Part 1: Setting it all up
'''

# we will need a euclidean_distance_algorithm that takes in
# two numpy arrays, and calculates the 
# euclidean distance between them

def euclidean_distance(np1, np2):
    return np.linalg.norm(np1-np2)

In [20]:
'''
Bring in the iris data from the web
iris_data ==
    2D numpy array of the four predictors of iris
        plus the species
'''

iris_data = pd.read_csv('https://raw.githubusercontent.com/HunterUSF/BetamoreDS/master/data/iris.csv')

# iris_data is a dataframe, but let's turn it into
# a 2D numpy array
# Hint: use .values to turn a dataframe into a 2d array

iris_data = iris_data.values
iris_data

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [21]:
iris_data[:, 0:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [22]:
iris_data[0, 0:4]

array([5.1, 3.5, 1.4, 0.2], dtype=object)

In [23]:
unknown = [6.3,  3.1 ,  5.1,  2.4]

In [24]:
euclidean_distance(unknown, iris_data[:, 0:4])

34.62340249022327

In [25]:
zip(unknown, iris_data[0])

[(6.3, 5.1), (3.1, 3.5), (5.1, 1.4), (2.4, 0.2)]

In [26]:
zip(unknown, iris_data[0])

[(6.3, 5.1), (3.1, 3.5), (5.1, 1.4), (2.4, 0.2)]

In [27]:
np.linalg.norm(unknown)

9.0038880490596949

In [28]:
print(unknown)
print(iris_data[0, :4])
unknown - iris_data[0, :4]

[6.3, 3.1, 5.1, 2.4]
[5.1 3.5 1.4 0.2]


array([1.2000000000000002, -0.3999999999999999, 3.6999999999999997,
       2.1999999999999997], dtype=object)

In [29]:
np.linalg.norm(unknown - iris_data[0, :4])

4.4866468548349108

In [30]:
euclidean_distance(unknown, iris_data[0, :4])

4.4866468548349108

In [31]:
tuple([euclidean_distance(unknown, iris_data[0, :4]), iris_data[0,4]])

(4.4866468548349108, 'Iris-setosa')

In [32]:
[tuple([iris_data[x,0], "Huzzah"]) for x in iris_data]

IndexError: arrays used as indices must be of integer (or boolean) type

In [33]:
[tuple([euclidean_distance(unknown, iris_data[x, :4]), iris_data[x,4]]) for x in iris_data]

IndexError: arrays used as indices must be of integer (or boolean) type

In [43]:
'''
Part 2: Predictions
Before we jump into making a general function,
let's try to predict 
unknown = [ 6.3,  3.1 ,  5.1,  2.4] with 3 neighbors
'''

# define our variables
unknown = [6.3,  3.1 ,  5.1,  2.4]
k = 3

# Make a list "distances" consisting of tuples
# Each tuple should be
# (euc_distance(unknown, data_point), species)
# for each data_point in iris_data
distances = [] # <FILL IN>

for i in range(len(iris_data)):
    distances.append(tuple([euclidean_distance(unknown, iris_data[i, :4]), iris_data[i,4]]))

distances

[(4.4866468548349108, 'Iris-setosa'),
 (4.5276925690687078, 'Iris-setosa'),
 (4.6743983570080969, 'Iris-setosa'),
 (4.5486261662176632, 'Iris-setosa'),
 (4.524378410345447, 'Iris-setosa'),
 (4.1243181254602561, 'Iris-setosa'),
 (4.591296113299598, 'Iris-setosa'),
 (4.4249293779675165, 'Iris-setosa'),
 (4.7095647357266461, 'Iris-setosa'),
 (4.495553358597804, 'Iris-setosa'),
 (4.3554563480765127, 'Iris-setosa'),
 (4.4079473681068375, 'Iris-setosa'),
 (4.608687448721164, 'Iris-setosa'),
 (5.0299105359837162, 'Iris-setosa'),
 (4.5945620030640564, 'Iris-setosa'),
 (4.3600458713183281, 'Iris-setosa'),
 (4.4598206241955518, 'Iris-setosa'),
 (4.4384682042344288, 'Iris-setosa'),
 (4.1012193308819755, 'Iris-setosa'),
 (4.3931765272977588, 'Iris-setosa'),
 (4.1593268686170832, 'Iris-setosa'),
 (4.3312815655415431, 'Iris-setosa'),
 (4.9789557138018408, 'Iris-setosa'),
 (4.080441152620633, 'Iris-setosa'),
 (4.1737273509418413, 'Iris-setosa'),
 (4.3347433603386483, 'Iris-setosa'),
 (4.2461747491124

In [44]:
#distances = np.array(distances)
distances

[(4.4866468548349108, 'Iris-setosa'),
 (4.5276925690687078, 'Iris-setosa'),
 (4.6743983570080969, 'Iris-setosa'),
 (4.5486261662176632, 'Iris-setosa'),
 (4.524378410345447, 'Iris-setosa'),
 (4.1243181254602561, 'Iris-setosa'),
 (4.591296113299598, 'Iris-setosa'),
 (4.4249293779675165, 'Iris-setosa'),
 (4.7095647357266461, 'Iris-setosa'),
 (4.495553358597804, 'Iris-setosa'),
 (4.3554563480765127, 'Iris-setosa'),
 (4.4079473681068375, 'Iris-setosa'),
 (4.608687448721164, 'Iris-setosa'),
 (5.0299105359837162, 'Iris-setosa'),
 (4.5945620030640564, 'Iris-setosa'),
 (4.3600458713183281, 'Iris-setosa'),
 (4.4598206241955518, 'Iris-setosa'),
 (4.4384682042344288, 'Iris-setosa'),
 (4.1012193308819755, 'Iris-setosa'),
 (4.3931765272977588, 'Iris-setosa'),
 (4.1593268686170832, 'Iris-setosa'),
 (4.3312815655415431, 'Iris-setosa'),
 (4.9789557138018408, 'Iris-setosa'),
 (4.080441152620633, 'Iris-setosa'),
 (4.1737273509418413, 'Iris-setosa'),
 (4.3347433603386483, 'Iris-setosa'),
 (4.2461747491124

In [35]:
# Grab the nearest k neighbors
nearest = [] # <FILL IN>

In [45]:
distances[:,0:1]

TypeError: list indices must be integers, not tuple

In [49]:
distances[0]

4.4866468548349108

In [47]:
type(distances[0][0])

numpy.float64

In [48]:
float(distances[:,0])

TypeError: list indices must be integers, not tuple